# -*- coding: utf-8 -*-
"""Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCWUyEwD8e_o0Y9C7ZcZAHqWWnJiIHnK
"""

from bs4 import BeautifulSoup
from urllib.request import urlopen
import os

pg = urlopen("https://www.espncricinfo.com/rankings/content/page/211271.html")
soup = BeautifulSoup(pg, 'html.parser')

body = soup.find('div', {"class" : "ciPhotoContainer"})
headings = soup.findAll('h3')

names = []
for h in headings:
  names.append(h.text)

import pandas as pd
column_names = ['Pos', 'Team', 'Matches', 'Points', 'Rating']
df = pd.DataFrame(columns=column_names)

path = "D:/"
tr_list = body.findAll('tr')
n=0
for i in tr_list:
  row = []
  td_list = i.findAll('td')
  for j in td_list:
    row.append(j.text)
  print(row)
  data={}
  try:
    for k in range(len(df.columns)):
      data[df.columns[k]] = row[k]
    df= df.append(data,ignore_index=True)
  except:
    df=pd.DataFrame(columns=column_names)
    table_name=names[n]
    n=n+1
df.to_csv('D:\\'+'Cricinfo'+table_name+'.csv', index = False)
print("done")

