# -*- coding: utf-8 -*-
"""DV with Accuweather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSc88zTE2V-mLiXm9s52C_zq7wjYvLl4
"""

import pandas as pd
df = pd.read_csv("./august.csv")
df = df.iloc[:, 1:]
df

import matplotlib.pyplot as plt
plt.plot(df['Date'],df['High_temp'])
plt.title("Date vs High Temperature", fontsize=20)
plt.xlabel("Date",fontsize=15)
plt.ylabel("High Temperature", fontsize=15)

import matplotlib.pyplot as plt
plt.subplot(1,2,1)
plt.plot(df['Date'],df['High_temp'])
plt.title("Date vs High Temperature",fontsize=20)
plt.xlabel("Date",fontsize=15)
plt.ylabel("High Temperature", fontsize=15)
plt.show()

plt.subplot(1,2,2)
plt.plot(df['Date'],df['Low_temp'])
plt.title("Date vs Low Temperature",fontsize=20)
plt.xlabel("Date",fontsize=15)
plt.ylabel("Low Temperature", fontsize=15)
plt.show
